{
 "title": "Rate Limiter Dashboard",
 "description": "golang rate limiter dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_total{status=\"incoming\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Allowed Requests",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_total{status=\"allowed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_total{status=\"blocked\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Requests %",
   "type": "stat",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(requests_total{status=\"blocked\"}[5m]))\n/\nsum(rate(requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency Panel", "type": "row", "gridPos": { "x": 0, "y": 18, "w": 24, "h": 1 } },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 19, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(requests_duration_seconds_sum[5m])/rate(requests_duration_seconds_count[5m]))*1000",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "p95 Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 19, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(requests_duration_seconds_bucket[5m])\n  )\n)*1000",
     "legendFormat": "p95 request latency"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(requests_duration_seconds_bucket[5m])\n  )\n)*1000",
     "legendFormat": "p99 requests latency"
    }
   ]
  },
  { "title": "Requests Per Second", "type": "row", "gridPos": { "x": 0, "y": 35, "w": 24, "h": 1 } },
  {
   "title": "Request Rate (rps)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{status=\"incoming\"}[1m])",
     "legendFormat": "requests_total rate"
    }
   ]
  },
  {
   "title": "Allowed Rps",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 36, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{status=\"allowed\"}[1m])",
     "legendFormat": "allowed_request_per_seconds"
    }
   ]
  },
  {
   "title": "Blocked Rps",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 44, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{status=\"blocked\"}[1m])",
     "legendFormat": "blocked_rps"
    }
   ]
  },
  { "title": "Fallback and Redis Errors", "type": "row", "gridPos": { "x": 0, "y": 52, "w": 24, "h": 1 } },
  {
   "title": "Total Redis Errors",
   "type": "stat",
   "gridPos": { "x": 0, "y": 53, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Errors Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 53, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(redis_errors_total[5m])", "legendFormat": "Redis Error Rate" }
   ]
  },
  {
   "title": "Total Fallback Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 61, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fallback_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fallback Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 61, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(fallback_request_total[5m])",
     "legendFormat": "Fallback Requests Rate"
    }
   ]
  }
 ]
}